### ISSUE TITLE
Binance app stopped working on Ubuntu 22.04

### ISSUE THREAD

**Issue by nullpntr** [binance/desktop#27]
After upgrade to Ubuntu 22.04 binance app won't starting 

Logs output:
(node:41803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 web-contents-created listeners added to [App]. Use emitter.setMaxListeners() to increase limit
(Use `binance --trace-warnings ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[41803:0507/095802.953840:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped) 

Any suggestion how to fix this issue?

**Comment by nullpntr** [comment]
Found a temporary fix that at least allows to run the app. Use --no-sandbox flag:
binance --no-sandbox

**Comment by pphotography** [comment]
I just upgraded to Xubuntu 22.04 (fresh install) and do have the same error when I try to start the binance desktop app I just downloaded today:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[49947:0807/212404.894839:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
With the workaround using no-sandbox I can start the application.

**Comment by LeadManPL** [comment]
After latest upgrade to PRETTY_NAME="Ubuntu 22.04.2 LTS" Application doesnt start even with this workaround:

```
patben@patben-amd:~$ binance --no-sandbox

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at P._deserialize (/opt/Binance/resources/app.asar/build/main.js:4:825850)
    at get store [as store] (/opt/Binance/resources/app.asar/build/main.js:4:829385)
    at new P (/opt/Binance/resources/app.asar/build/main.js:4:827120)
    at new e.exports (/opt/Binance/resources/app.asar/build/main.js:1:123869)
    at Module.<anonymous> (/opt/Binance/resources/app.asar/build/main.js:4:510940)
    at n (/opt/Binance/resources/app.asar/build/main.js:1:118)
    at Object.<anonymous> (/opt/Binance/resources/app.asar/build/main.js:1:19336)
    at n (/opt/Binance/resources/app.asar/build/main.js:1:118)
    at Object.<anonymous> (/opt/Binance/resources/app.asar/build/main.js:1:78829)
```
